# Generated by Django 5.0 on 2023-12-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='productname', max_length=20, verbose_name='Name of the Product')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
